<?php

use Illuminate\Database\Seeder;

class empresa_juradaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('empresa_juradas')->insert(array(
            array(
                "id" => 4,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 9651465,
                "anot" => 2019,
                "empresa_id" => 2,
                "jurada_id" => 21,
                "created_at" => NULL,
                "updated_at" => "2019-03-21 12:21:22",
            ),
            array(
                "id" => 20,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 963101,
                "anot" => 2019,
                "empresa_id" => 4,
                "jurada_id" => 23,
                "created_at" => NULL,
                "updated_at" => "2019-03-21 13:12:48",
            ),
            array(
                "id" => 21,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 9643546,
                "anot" => 2019,
                "empresa_id" => 2,
                "jurada_id" => 24,
                "created_at" => NULL,
                "updated_at" => "2019-03-21 12:22:53",
            ),
            array(
                "id" => 22,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 960601,
                "anot" => 2019,
                "empresa_id" => 2,
                "jurada_id" => 23,
                "created_at" => NULL,
                "updated_at" => "2019-04-27 12:02:34",
            ),
            array(
                "id" => 23,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 160601,
                "anot" => 2019,
                "empresa_id" => 2,
                "jurada_id" => 27,
                "created_at" => NULL,
                "updated_at" => "2019-05-06 12:24:53",
            ),
            array(
                "id" => 24,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 160601,
                "anot" => 2019,
                "empresa_id" => 2,
                "jurada_id" => 28,
                "created_at" => NULL,
                "updated_at" => "2019-04-15 10:51:14",
            ),
            array(
                "id" => 27,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 9845210,
                "anot" => 2019,
                "empresa_id" => 4,
                "jurada_id" => 24,
                "created_at" => NULL,
                "updated_at" => "2019-03-30 10:17:50",
            ),
            array(
                "id" => 31,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 10019017,
                "anot" => 2019,
                "empresa_id" => 4,
                "jurada_id" => 21,
                "created_at" => NULL,
                "updated_at" => "2019-04-15 10:55:21",
            ),
            array(
                "id" => 32,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 163101,
                "anot" => 2019,
                "empresa_id" => 4,
                "jurada_id" => 30,
                "created_at" => NULL,
                "updated_at" => "2019-04-29 11:32:26",
            ),
            array(
                "id" => 33,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 163101,
                "anot" => 2019,
                "empresa_id" => 4,
                "jurada_id" => 20,
                "created_at" => NULL,
                "updated_at" => "2019-03-22 12:56:30",
            ),
            array(
                "id" => 34,
                "arti_id" => 57,
                "estado" => "D.J. Observada",
                "folio" => 163101,
                "anot" => 2019,
                "empresa_id" => 4,
                "jurada_id" => 31,
                "created_at" => NULL,
                "updated_at" => "2019-04-29 11:31:14",
            ),
            array(
                "id" => 35,
                "arti_id" => 53,
                "estado" => "Pendiente por declarar",
                "folio" => NULL,
                "anot" => 2019,
                "empresa_id" => 3,
                "jurada_id" => 21,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 36,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 1775283,
                "anot" => 2019,
                "empresa_id" => 3,
                "jurada_id" => 25,
                "created_at" => NULL,
                "updated_at" => "2019-04-29 11:28:04",
            ),
            array(
                "id" => 37,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 161001,
                "anot" => 2019,
                "empresa_id" => 3,
                "jurada_id" => 26,
                "created_at" => NULL,
                "updated_at" => "2019-05-06 13:03:20",
            ),
            array(
                "id" => 38,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 9758521,
                "anot" => 2019,
                "empresa_id" => 3,
                "jurada_id" => 24,
                "created_at" => NULL,
                "updated_at" => "2019-03-21 13:07:42",
            ),
            array(
                "id" => 39,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 961001,
                "anot" => 2019,
                "empresa_id" => 3,
                "jurada_id" => 23,
                "created_at" => NULL,
                "updated_at" => "2019-04-15 10:53:52",
            ),
            array(
                "id" => 40,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 161001,
                "anot" => 2019,
                "empresa_id" => 3,
                "jurada_id" => 27,
                "created_at" => NULL,
                "updated_at" => "2020-02-26 13:28:34",
            ),
            array(
                "id" => 41,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 161001,
                "anot" => 2019,
                "empresa_id" => 3,
                "jurada_id" => 28,
                "created_at" => NULL,
                "updated_at" => "2019-03-29 12:40:33",
            ),
            array(
                "id" => 42,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 161001,
                "anot" => 2019,
                "empresa_id" => 3,
                "jurada_id" => 29,
                "created_at" => NULL,
                "updated_at" => "2019-03-29 12:41:06",
            ),
            array(
                "id" => 43,
                "arti_id" => 53,
                "estado" => "D.J. Aceptada",
                "folio" => NULL,
                "anot" => 2019,
                "empresa_id" => 1,
                "jurada_id" => 23,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 44,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 10032231,
                "anot" => 2019,
                "empresa_id" => 5,
                "jurada_id" => 21,
                "created_at" => NULL,
                "updated_at" => "2019-04-15 10:57:08",
            ),
            array(
                "id" => 45,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 171601,
                "anot" => 2019,
                "empresa_id" => 5,
                "jurada_id" => 26,
                "created_at" => NULL,
                "updated_at" => "2019-05-06 12:43:54",
            ),
            array(
                "id" => 46,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 9858927,
                "anot" => 2019,
                "empresa_id" => 5,
                "jurada_id" => 24,
                "created_at" => NULL,
                "updated_at" => "2019-03-22 14:35:42",
            ),
            array(
                "id" => 47,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 971601,
                "anot" => 2019,
                "empresa_id" => 5,
                "jurada_id" => 23,
                "created_at" => NULL,
                "updated_at" => "2019-05-02 14:05:11",
            ),
            array(
                "id" => 48,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 171601,
                "anot" => 2019,
                "empresa_id" => 5,
                "jurada_id" => 30,
                "created_at" => NULL,
                "updated_at" => "2019-05-06 12:42:30",
            ),
            array(
                "id" => 49,
                "arti_id" => 57,
                "estado" => "D.J. Observada",
                "folio" => 171601,
                "anot" => 2019,
                "empresa_id" => 5,
                "jurada_id" => 31,
                "created_at" => NULL,
                "updated_at" => "2019-05-06 12:42:02",
            ),
            array(
                "id" => 51,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 2065512,
                "anot" => 2019,
                "empresa_id" => 5,
                "jurada_id" => 32,
                "created_at" => NULL,
                "updated_at" => "2019-05-06 12:44:29",
            ),
            array(
                "id" => 52,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 960501,
                "anot" => 2019,
                "empresa_id" => 6,
                "jurada_id" => 23,
                "created_at" => NULL,
                "updated_at" => "2019-05-02 16:05:04",
            ),
            array(
                "id" => 53,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 260631,
                "anot" => 2019,
                "empresa_id" => 6,
                "jurada_id" => 21,
                "created_at" => NULL,
                "updated_at" => "2019-03-30 10:20:31",
            ),
            array(
                "id" => 54,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 160501,
                "anot" => 2019,
                "empresa_id" => 6,
                "jurada_id" => 26,
                "created_at" => NULL,
                "updated_at" => "2019-05-06 12:48:24",
            ),
            array(
                "id" => 55,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 10017825,
                "anot" => 2019,
                "empresa_id" => 6,
                "jurada_id" => 24,
                "created_at" => NULL,
                "updated_at" => "2019-03-26 09:18:38",
            ),
            array(
                "id" => 56,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 2066252,
                "anot" => 2019,
                "empresa_id" => 6,
                "jurada_id" => 32,
                "created_at" => NULL,
                "updated_at" => "2019-05-06 12:48:56",
            ),
            array(
                "id" => 57,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 160501,
                "anot" => 2019,
                "empresa_id" => 6,
                "jurada_id" => 30,
                "created_at" => NULL,
                "updated_at" => "2019-05-02 16:06:33",
            ),
            array(
                "id" => 58,
                "arti_id" => 57,
                "estado" => "D.J. Observada",
                "folio" => 160501,
                "anot" => 2019,
                "empresa_id" => 6,
                "jurada_id" => 31,
                "created_at" => NULL,
                "updated_at" => "2019-05-06 12:47:36",
            ),
            array(
                "id" => 60,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 224171,
                "anot" => 2019,
                "empresa_id" => 7,
                "jurada_id" => 21,
                "created_at" => NULL,
                "updated_at" => "2019-03-30 10:24:04",
            ),
            array(
                "id" => 61,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 160201,
                "anot" => 2019,
                "empresa_id" => 7,
                "jurada_id" => 26,
                "created_at" => NULL,
                "updated_at" => "2019-05-10 13:40:07",
            ),
            array(
                "id" => 62,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 9845622,
                "anot" => 2019,
                "empresa_id" => 7,
                "jurada_id" => 24,
                "created_at" => NULL,
                "updated_at" => "2019-03-22 14:39:07",
            ),
            array(
                "id" => 63,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 960201,
                "anot" => 2019,
                "empresa_id" => 7,
                "jurada_id" => 23,
                "created_at" => NULL,
                "updated_at" => "2019-03-21 13:32:22",
            ),
            array(
                "id" => 64,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 160201,
                "anot" => 2019,
                "empresa_id" => 7,
                "jurada_id" => 27,
                "created_at" => NULL,
                "updated_at" => "2019-05-06 12:23:08",
            ),
            array(
                "id" => 65,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 160201,
                "anot" => 2019,
                "empresa_id" => 7,
                "jurada_id" => 28,
                "created_at" => NULL,
                "updated_at" => "2019-03-29 12:49:05",
            ),
            array(
                "id" => 67,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 10025712,
                "anot" => 2019,
                "empresa_id" => 8,
                "jurada_id" => 21,
                "created_at" => NULL,
                "updated_at" => "2019-04-15 11:01:02",
            ),
            array(
                "id" => 68,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 9851129,
                "anot" => 2019,
                "empresa_id" => 8,
                "jurada_id" => 24,
                "created_at" => NULL,
                "updated_at" => "2019-03-22 14:40:17",
            ),
            array(
                "id" => 69,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 964401,
                "anot" => 2019,
                "empresa_id" => 8,
                "jurada_id" => 23,
                "created_at" => NULL,
                "updated_at" => "2019-03-21 13:35:36",
            ),
            array(
                "id" => 70,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 164401,
                "anot" => 2019,
                "empresa_id" => 8,
                "jurada_id" => 30,
                "created_at" => NULL,
                "updated_at" => "2019-05-02 16:11:35",
            ),
            array(
                "id" => 71,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 164401,
                "anot" => 2019,
                "empresa_id" => 8,
                "jurada_id" => 31,
                "created_at" => NULL,
                "updated_at" => "2019-05-02 16:11:48",
            ),
            array(
                "id" => 72,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 164401,
                "anot" => 2019,
                "empresa_id" => 8,
                "jurada_id" => 20,
                "created_at" => NULL,
                "updated_at" => "2019-03-22 14:40:02",
            ),
            array(
                "id" => 73,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 9846068,
                "anot" => 2019,
                "empresa_id" => 9,
                "jurada_id" => 24,
                "created_at" => NULL,
                "updated_at" => "2019-03-22 14:41:03",
            ),
            array(
                "id" => 76,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 265791,
                "anot" => 2019,
                "empresa_id" => 6,
                "jurada_id" => 22,
                "created_at" => NULL,
                "updated_at" => "2019-03-30 10:20:51",
            ),
            array(
                "id" => 77,
                "arti_id" => 57,
                "estado" => "D.J. Observada",
                "folio" => 162301,
                "anot" => 2019,
                "empresa_id" => 9,
                "jurada_id" => 27,
                "created_at" => NULL,
                "updated_at" => "2019-04-15 11:02:54",
            ),
            array(
                "id" => 78,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 162301,
                "anot" => 2019,
                "empresa_id" => 9,
                "jurada_id" => 28,
                "created_at" => NULL,
                "updated_at" => "2019-04-15 11:03:18",
            ),
            array(
                "id" => 79,
                "arti_id" => 57,
                "estado" => "D.J. Observada",
                "folio" => 162501,
                "anot" => 2019,
                "empresa_id" => 10,
                "jurada_id" => 27,
                "created_at" => NULL,
                "updated_at" => "2019-05-02 16:17:16",
            ),
            array(
                "id" => 80,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 162501,
                "anot" => 2019,
                "empresa_id" => 10,
                "jurada_id" => 28,
                "created_at" => NULL,
                "updated_at" => "2019-04-15 11:04:51",
            ),
            array(
                "id" => 81,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 175601,
                "anot" => 2019,
                "empresa_id" => 11,
                "jurada_id" => 27,
                "created_at" => NULL,
                "updated_at" => "2019-05-06 13:00:00",
            ),
            array(
                "id" => 82,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 175601,
                "anot" => 2019,
                "empresa_id" => 11,
                "jurada_id" => 28,
                "created_at" => NULL,
                "updated_at" => "2019-04-15 11:06:26",
            ),
            array(
                "id" => 83,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 175601,
                "anot" => 2019,
                "empresa_id" => 11,
                "jurada_id" => 29,
                "created_at" => NULL,
                "updated_at" => "2019-04-15 11:06:37",
            ),
            array(
                "id" => 84,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 171601,
                "anot" => 2019,
                "empresa_id" => 5,
                "jurada_id" => 33,
                "created_at" => NULL,
                "updated_at" => "2019-04-13 12:43:51",
            ),
            array(
                "id" => 85,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 61031626,
                "anot" => 2019,
                "empresa_id" => 6,
                "jurada_id" => 33,
                "created_at" => NULL,
                "updated_at" => "2019-04-15 10:38:45",
            ),
            array(
                "id" => 86,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 235507,
                "anot" => 2019,
                "empresa_id" => 7,
                "jurada_id" => 22,
                "created_at" => NULL,
                "updated_at" => "2019-05-06 12:53:30",
            ),
            array(
                "id" => 94,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 169460,
                "anot" => 2020,
                "empresa_id" => 2,
                "jurada_id" => 24,
                "created_at" => NULL,
                "updated_at" => "2020-03-10 20:37:55",
            ),
            array(
                "id" => 95,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 3311922,
                "anot" => 2020,
                "empresa_id" => 2,
                "jurada_id" => 21,
                "created_at" => NULL,
                "updated_at" => "2020-03-18 16:09:31",
            ),
            array(
                "id" => 96,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 960601,
                "anot" => 2020,
                "empresa_id" => 2,
                "jurada_id" => 23,
                "created_at" => NULL,
                "updated_at" => "2020-03-13 15:32:16",
            ),
            array(
                "id" => 97,
                "arti_id" => 57,
                "estado" => "D.J. Observada",
                "folio" => 160601,
                "anot" => 2020,
                "empresa_id" => 2,
                "jurada_id" => 27,
                "created_at" => NULL,
                "updated_at" => "2020-04-07 10:28:53",
            ),
            array(
                "id" => 98,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 160601,
                "anot" => 2020,
                "empresa_id" => 2,
                "jurada_id" => 28,
                "created_at" => NULL,
                "updated_at" => "2020-03-28 11:40:28",
            ),
            array(
                "id" => 99,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 4074120,
                "anot" => 2020,
                "empresa_id" => 4,
                "jurada_id" => 21,
                "created_at" => NULL,
                "updated_at" => "2020-03-28 11:45:15",
            ),
            array(
                "id" => 100,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 3282718,
                "anot" => 2020,
                "empresa_id" => 4,
                "jurada_id" => 24,
                "created_at" => NULL,
                "updated_at" => "2020-03-27 13:30:54",
            ),
            array(
                "id" => 101,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 963101,
                "anot" => 2020,
                "empresa_id" => 4,
                "jurada_id" => 23,
                "created_at" => NULL,
                "updated_at" => "2020-03-13 15:51:07",
            ),
            array(
                "id" => 102,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 163101,
                "anot" => 2020,
                "empresa_id" => 4,
                "jurada_id" => 30,
                "created_at" => NULL,
                "updated_at" => "2020-05-09 18:00:08",
            ),
            array(
                "id" => 103,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 163101,
                "anot" => 2020,
                "empresa_id" => 4,
                "jurada_id" => 31,
                "created_at" => NULL,
                "updated_at" => "2020-03-28 11:44:13",
            ),
            array(
                "id" => 104,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 163101,
                "anot" => 2020,
                "empresa_id" => 4,
                "jurada_id" => 20,
                "created_at" => NULL,
                "updated_at" => "2020-03-28 11:44:31",
            ),
            array(
                "id" => 105,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 6138718,
                "anot" => 2020,
                "empresa_id" => 3,
                "jurada_id" => 26,
                "created_at" => NULL,
                "updated_at" => "2020-05-09 17:54:50",
            ),
            array(
                "id" => 106,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 134886,
                "anot" => 2020,
                "empresa_id" => 3,
                "jurada_id" => 24,
                "created_at" => NULL,
                "updated_at" => "2020-03-11 13:01:26",
            ),
            array(
                "id" => 107,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 161001,
                "anot" => 2020,
                "empresa_id" => 3,
                "jurada_id" => 27,
                "created_at" => NULL,
                "updated_at" => "2020-03-28 11:56:17",
            ),
            array(
                "id" => 108,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 160001,
                "anot" => 2020,
                "empresa_id" => 3,
                "jurada_id" => 28,
                "created_at" => NULL,
                "updated_at" => "2020-03-28 11:56:33",
            ),
            array(
                "id" => 109,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 160001,
                "anot" => 2020,
                "empresa_id" => 3,
                "jurada_id" => 29,
                "created_at" => NULL,
                "updated_at" => "2020-03-28 11:56:46",
            ),
            array(
                "id" => 110,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 33134436,
                "anot" => 2020,
                "empresa_id" => 7,
                "jurada_id" => 21,
                "created_at" => NULL,
                "updated_at" => "2020-03-18 17:01:02",
            ),
            array(
                "id" => 111,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 6212109,
                "anot" => 2020,
                "empresa_id" => 7,
                "jurada_id" => 26,
                "created_at" => NULL,
                "updated_at" => "2020-05-09 13:04:55",
            ),
            array(
                "id" => 112,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 3261162,
                "anot" => 2020,
                "empresa_id" => 7,
                "jurada_id" => 24,
                "created_at" => NULL,
                "updated_at" => "2020-03-18 17:01:21",
            ),
            array(
                "id" => 113,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 960201,
                "anot" => 2020,
                "empresa_id" => 7,
                "jurada_id" => 23,
                "created_at" => NULL,
                "updated_at" => "2020-03-18 17:01:34",
            ),
            array(
                "id" => 114,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 16021,
                "anot" => 2020,
                "empresa_id" => 7,
                "jurada_id" => 27,
                "created_at" => NULL,
                "updated_at" => "2020-04-02 12:03:44",
            ),
            array(
                "id" => 115,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 16021,
                "anot" => 2020,
                "empresa_id" => 7,
                "jurada_id" => 28,
                "created_at" => NULL,
                "updated_at" => "2020-04-02 12:04:12",
            ),
            array(
                "id" => 116,
                "arti_id" => NULL,
                "estado" => "Pendiente por declarar",
                "folio" => NULL,
                "anot" => 2020,
                "empresa_id" => 7,
                "jurada_id" => 29,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 117,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 66886645,
                "anot" => 2020,
                "empresa_id" => 6,
                "jurada_id" => 21,
                "created_at" => NULL,
                "updated_at" => "2020-03-28 12:31:26",
            ),
            array(
                "id" => 118,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 160501,
                "anot" => 2020,
                "empresa_id" => 6,
                "jurada_id" => 26,
                "created_at" => NULL,
                "updated_at" => "2020-05-09 13:20:23",
            ),
            array(
                "id" => 119,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 201565,
                "anot" => 2020,
                "empresa_id" => 6,
                "jurada_id" => 24,
                "created_at" => NULL,
                "updated_at" => "2020-03-11 21:12:10",
            ),
            array(
                "id" => 120,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 960501,
                "anot" => 2020,
                "empresa_id" => 6,
                "jurada_id" => 23,
                "created_at" => NULL,
                "updated_at" => "2020-03-13 19:00:27",
            ),
            array(
                "id" => 121,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 160501,
                "anot" => 2020,
                "empresa_id" => 6,
                "jurada_id" => 30,
                "created_at" => NULL,
                "updated_at" => "2020-05-09 13:19:50",
            ),
            array(
                "id" => 122,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 160501,
                "anot" => 2020,
                "empresa_id" => 6,
                "jurada_id" => 31,
                "created_at" => NULL,
                "updated_at" => "2020-05-09 13:18:56",
            ),
            array(
                "id" => 123,
                "arti_id" => NULL,
                "estado" => "Pendiente por declarar",
                "folio" => NULL,
                "anot" => 2020,
                "empresa_id" => 6,
                "jurada_id" => 20,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 124,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 3317575,
                "anot" => 2020,
                "empresa_id" => 8,
                "jurada_id" => 21,
                "created_at" => NULL,
                "updated_at" => "2020-03-18 17:05:16",
            ),
            array(
                "id" => 125,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 58806,
                "anot" => 2020,
                "empresa_id" => 8,
                "jurada_id" => 24,
                "created_at" => NULL,
                "updated_at" => "2020-03-11 21:29:11",
            ),
            array(
                "id" => 126,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 964401,
                "anot" => 2020,
                "empresa_id" => 8,
                "jurada_id" => 23,
                "created_at" => NULL,
                "updated_at" => "2020-03-13 18:19:32",
            ),
            array(
                "id" => 127,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 164402,
                "anot" => 2020,
                "empresa_id" => 8,
                "jurada_id" => 30,
                "created_at" => NULL,
                "updated_at" => "2020-05-09 16:27:47",
            ),
            array(
                "id" => 128,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 164401,
                "anot" => 2020,
                "empresa_id" => 8,
                "jurada_id" => 31,
                "created_at" => NULL,
                "updated_at" => "2020-05-09 18:20:16",
            ),
            array(
                "id" => 129,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 164402,
                "anot" => 2020,
                "empresa_id" => 8,
                "jurada_id" => 20,
                "created_at" => NULL,
                "updated_at" => "2020-03-28 12:20:08",
            ),
            array(
                "id" => 130,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 3308367,
                "anot" => 2020,
                "empresa_id" => 5,
                "jurada_id" => 21,
                "created_at" => NULL,
                "updated_at" => "2020-03-14 12:11:04",
            ),
            array(
                "id" => 131,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 6305208,
                "anot" => 2020,
                "empresa_id" => 5,
                "jurada_id" => 26,
                "created_at" => NULL,
                "updated_at" => "2020-05-09 16:07:16",
            ),
            array(
                "id" => 132,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 171601,
                "anot" => 2020,
                "empresa_id" => 5,
                "jurada_id" => 30,
                "created_at" => NULL,
                "updated_at" => "2020-03-28 12:38:26",
            ),
            array(
                "id" => 133,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 171601,
                "anot" => 2020,
                "empresa_id" => 5,
                "jurada_id" => 31,
                "created_at" => NULL,
                "updated_at" => "2020-03-28 12:38:38",
            ),
            array(
                "id" => 134,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 171601,
                "anot" => 2020,
                "empresa_id" => 5,
                "jurada_id" => 20,
                "created_at" => NULL,
                "updated_at" => "2020-03-28 12:38:53",
            ),
            array(
                "id" => 135,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 179821,
                "anot" => 2020,
                "empresa_id" => 5,
                "jurada_id" => 24,
                "created_at" => NULL,
                "updated_at" => "2020-03-12 12:19:55",
            ),
            array(
                "id" => 136,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 971601,
                "anot" => 2020,
                "empresa_id" => 5,
                "jurada_id" => 23,
                "created_at" => NULL,
                "updated_at" => "2020-03-13 19:23:26",
            ),
            array(
                "id" => 137,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 68024,
                "anot" => 2020,
                "empresa_id" => 13,
                "jurada_id" => 24,
                "created_at" => NULL,
                "updated_at" => "2020-03-13 13:38:30",
            ),
            array(
                "id" => 138,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 3430517,
                "anot" => 2020,
                "empresa_id" => 13,
                "jurada_id" => 23,
                "created_at" => NULL,
                "updated_at" => "2020-03-18 16:56:06",
            ),
            array(
                "id" => 139,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 3433188,
                "anot" => 2020,
                "empresa_id" => 12,
                "jurada_id" => 23,
                "created_at" => NULL,
                "updated_at" => "2020-03-17 17:41:40",
            ),
            array(
                "id" => 140,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 5647074,
                "anot" => 2020,
                "empresa_id" => 12,
                "jurada_id" => 34,
                "created_at" => NULL,
                "updated_at" => "2020-05-09 17:56:47",
            ),
            array(
                "id" => 141,
                "arti_id" => 57,
                "estado" => "D.J. Observada",
                "folio" => 5646586,
                "anot" => 2020,
                "empresa_id" => 13,
                "jurada_id" => 34,
                "created_at" => NULL,
                "updated_at" => "2020-05-09 17:53:07",
            ),
            array(
                "id" => 142,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 961001,
                "anot" => 2020,
                "empresa_id" => 3,
                "jurada_id" => 23,
                "created_at" => NULL,
                "updated_at" => "2020-03-13 17:51:10",
            ),
            array(
                "id" => 143,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 4091080,
                "anot" => 2020,
                "empresa_id" => 6,
                "jurada_id" => 33,
                "created_at" => "2020-03-27 13:48:36",
                "updated_at" => "2020-03-28 12:31:48",
            ),
            array(
                "id" => 144,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 4017845,
                "anot" => 2020,
                "empresa_id" => 5,
                "jurada_id" => 33,
                "created_at" => NULL,
                "updated_at" => "2020-03-28 12:37:32",
            ),
            array(
                "id" => 145,
                "arti_id" => 57,
                "estado" => "D.J. Observada",
                "folio" => 4083051,
                "anot" => 2020,
                "empresa_id" => 7,
                "jurada_id" => 22,
                "created_at" => NULL,
                "updated_at" => "2020-04-02 12:04:27",
            ),
            array(
                "id" => 146,
                "arti_id" => 57,
                "estado" => "D.J. Observada",
                "folio" => 4091080,
                "anot" => 2020,
                "empresa_id" => 6,
                "jurada_id" => 22,
                "created_at" => NULL,
                "updated_at" => "2020-04-02 12:06:42",
            ),
            array(
                "id" => 147,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 160601,
                "anot" => 2020,
                "empresa_id" => 2,
                "jurada_id" => 29,
                "created_at" => NULL,
                "updated_at" => "2020-03-28 11:40:48",
            ),
            array(
                "id" => 148,
                "arti_id" => 57,
                "estado" => "D.J. Observada",
                "folio" => 162301,
                "anot" => 2020,
                "empresa_id" => 9,
                "jurada_id" => 27,
                "created_at" => NULL,
                "updated_at" => "2020-04-07 10:39:32",
            ),
            array(
                "id" => 149,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 162301,
                "anot" => 2020,
                "empresa_id" => 9,
                "jurada_id" => 28,
                "created_at" => NULL,
                "updated_at" => "2020-04-07 10:39:51",
            ),
            array(
                "id" => 150,
                "arti_id" => NULL,
                "estado" => "Pendiente por declarar",
                "folio" => NULL,
                "anot" => 2020,
                "empresa_id" => 9,
                "jurada_id" => 29,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 151,
                "arti_id" => 57,
                "estado" => "D.J. Observada",
                "folio" => 175601,
                "anot" => 2020,
                "empresa_id" => 11,
                "jurada_id" => 27,
                "created_at" => NULL,
                "updated_at" => "2020-04-07 10:44:52",
            ),
            array(
                "id" => 152,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 175601,
                "anot" => 2020,
                "empresa_id" => 11,
                "jurada_id" => 28,
                "created_at" => NULL,
                "updated_at" => "2020-04-07 10:45:07",
            ),
            array(
                "id" => 153,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 175601,
                "anot" => 2020,
                "empresa_id" => 11,
                "jurada_id" => 29,
                "created_at" => NULL,
                "updated_at" => "2020-04-07 10:45:22",
            ),
            array(
                "id" => 154,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 162501,
                "anot" => 2020,
                "empresa_id" => 10,
                "jurada_id" => 27,
                "created_at" => NULL,
                "updated_at" => "2020-05-09 16:24:54",
            ),
            array(
                "id" => 155,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 162501,
                "anot" => 2020,
                "empresa_id" => 10,
                "jurada_id" => 28,
                "created_at" => NULL,
                "updated_at" => "2020-04-07 10:49:49",
            ),
            array(
                "id" => 156,
                "arti_id" => 53,
                "estado" => "Pendiente por declarar",
                "folio" => NULL,
                "anot" => 2020,
                "empresa_id" => 10,
                "jurada_id" => 29,
                "created_at" => NULL,
                "updated_at" => "2020-05-09 16:24:41",
            ),
            array(
                "id" => 157,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 6302109,
                "anot" => 2020,
                "empresa_id" => 5,
                "jurada_id" => 32,
                "created_at" => NULL,
                "updated_at" => "2020-05-09 16:11:34",
            ),
            array(
                "id" => 158,
                "arti_id" => 55,
                "estado" => "D.J. Aceptada",
                "folio" => 6302109,
                "anot" => 2020,
                "empresa_id" => 6,
                "jurada_id" => 32,
                "created_at" => NULL,
                "updated_at" => "2020-05-09 16:18:27",
            ),
        ));
    }
}
